# Generated by Django 5.2.8 on 2025-11-11 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('nombre_artista', models.CharField(max_length=100, verbose_name='Nombre del Artista')),
                ('imagen', models.ImageField(upload_to='portadas_canciones/', verbose_name='Imagen de Portada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
        ),
    ]
