# Generated by Django 5.2.8 on 2025-11-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Imagen')),
                ('link', models.URLField(max_length=500, verbose_name='Enlace')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
